### ISSUE TITLE
Create repo from scratch

### ISSUE THREAD

**Issue by joelsewhere** [learn-co-curriculum/dsc-project-template#2]
Once students have been introduced to this repo organization, I think either in mod 2 or 3 students should be walked through the process of creating a project repo from scratch.

Because the majority of their work, including their end of mod projects, involve forking a learn repo, I've found that students often do not know how to create a project from scratch. (ie create an empty github repo and push to it)

Personal preference is to work [hub](https://hub.github.com/#developer) into the workflow to encourage students to use the command line. Also aliasing, but that isn't as important

Thinking about this, it might make sense to create a PyPI package that would initiate a vanilla data science repository structure. I would love that for my own life, would probably lead to  more organized student repos, and would be a nice tool for students after graduating.

**Comment by bpurdy-ds** [comment]
We'll keep this in mind as we work on v3.0. https://github.com/learn-co-curriculum/dsc-project-template/issues/2#issue-598040251
